### ISSUE TITLE
Kwai-Kolors node doesn't install

### ISSUE THREAD

**Issue by ql0wn4** [Kwai-Kolors/Kolors#153]
Impossible to install Kwai-Kolors from ComfyUi Manager. Tried several times, this is the error:

# ComfyUI Error Report
## Error Details
- **Node Type:** DownloadAndLoadKolorsModel
- **Exception Type:** OSError
- **Exception Message:** Error no file named scheduler_config.json found in directory E:\Stable-Diffusion\ComfyUI\ComfyUI\models\diffusers\Kolors.
## Stack Trace
```
  File "E:\Stable-Diffusion\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Stable-Diffusion\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Stable-Diffusion\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "E:\Stable-Diffusion\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper\nodes.py", line 77, in loadmodel
    scheduler = EulerDiscreteScheduler.from_pretrained(model_path, subfolder= 'scheduler')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\Stable-Diffusion\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^

  File "E:\Stable-Diffusion\ComfyUI\python_embeded\Lib\site-packages\diffusers\schedulers\scheduling_utils.py", line 150, in from_pretrained
    config, kwargs, commit_hash = cls.load_config(
                                  ^^^^^^^^^^^^^^^^

  File "E:\Stable-Diffusion\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^

  File "E:\Stable-Diffusion\ComfyUI\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 373, in load_config
    raise EnvironmentError(

```
## System Information
- **ComfyUI Version:** v0.2.2-84-gd1cdf51
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.1.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3080 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12884377600
  - **VRAM Free:** 11464735848
  - **Torch VRAM Total:** 201326592
  - **Torch VRAM Free:** 129629288

## Logs
```
2024-10-02 06:38:38,623 - root - INFO - Total VRAM 12288 MB, total RAM 32682 MB
2024-10-02 06:38:38,624 - root - INFO - pytorch version: 2.1.1+cu121
2024-10-02 06:38:38,625 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-02 06:38:38,625 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3080 Ti : cudaMallocAsync
2024-10-02 06:38:40,258 - root - INFO - Using pytorch cross attention
2024-10-02 06:38:42,115 - root - INFO - [Prompt Server] web root: E:\Stable-Diffusion\ComfyUI\ComfyUI\web
2024-10-02 06:38:42,117 - root - INFO - Adding extra search path checkpoints E:\Stable-Diffusion\stable-diffusion-webui\models/Stable-diffusion
2024-10-02 06:38:42,117 - root - INFO - Adding extra search path configs E:\Stable-Diffusion\stable-diffusion-webui\models/Stable-diffusion
2024-10-02 06:38:42,117 - root - INFO - Adding extra search path vae E:\Stable-Diffusion\stable-diffusion-webui\models/VAE
2024-10-02 06:38:42,117 - root - INFO - Adding extra search path loras E:\Stable-Diffusion\stable-diffusion-webui\models/Lora
2024-10-02 06:38:42,117 - root - INFO - Adding extra search path loras E:\Stable-Diffusion\stable-diffusion-webui\models/LyCORIS
2024-10-02 06:38:42,117 - root - INFO - Adding extra search path upscale_models E:\Stable-Diffusion\stable-diffusion-webui\models/ESRGAN
2024-10-02 06:38:42,117 - root - INFO - Adding extra search path upscale_models E:\Stable-Diffusion\stable-diffusion-webui\models/RealESRGAN
2024-10-02 06:38:42,118 - root - INFO - Adding extra search path upscale_models E:\Stable-Diffusion\stable-diffusion-webui\models/SwinIR
2024-10-02 06:38:42,118 - root - INFO - Adding extra search path embeddings E:\Stable-Diffusion\stable-diffusion-webui\embeddings
2024-10-02 06:38:42,118 - root - INFO - Adding extra search path hypernetworks E:\Stable-Diffusion\stable-diffusion-webui\models/hypernetworks
2024-10-02 06:38:42,118 - root - INFO - Adding extra search path controlnet E:\Stable-Diffusion\stable-diffusion-webui\extensions\sd-webui-controlnet\models
2024-10-02 06:38:50,122 - root - INFO - Total VRAM 12288 MB, total RAM 32682 MB
2024-10-02 06:38:50,122 - root - INFO - pytorch version: 2.1.1+cu121
2024-10-02 06:38:50,123 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-02 06:38:50,123 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3080 Ti : cudaMallocAsync
2024-10-02 06:38:51,435 - root - INFO - --------------
2024-10-02 06:38:51,435 - root - INFO - [91m ### Mixlab Nodes: [93mLoaded
2024-10-02 06:38:51,435 - root - INFO - ChatGPT.available True
2024-10-02 06:38:51,436 - root - INFO - edit_mask.available True
2024-10-02 06:38:51,448 - root - INFO - LaMaInpainting.available True
2024-10-02 06:38:52,095 - root - INFO - ClipInterrogator.available True
2024-10-02 06:38:52,444 - root - INFO - PromptGenerate.available True
2024-10-02 06:38:52,444 - root - INFO - ChinesePrompt.available True
2024-10-02 06:38:52,445 - root - INFO - RembgNode_.available True
2024-10-02 06:38:53,445 - root - INFO - TripoSR.available
2024-10-02 06:38:53,447 - root - INFO - MiniCPMNode.available
2024-10-02 06:38:53,524 - root - INFO - Scenedetect.available
2024-10-02 06:38:53,535 - root - INFO - FishSpeech.available False
2024-10-02 06:38:53,538 - root - INFO - SenseVoice.available False
2024-10-02 06:38:53,538 - root - INFO - [93m -------------- [0m
2024-10-02 06:38:55,021 - py.warnings - WARNING - E:\Stable-Diffusion\ComfyUI\python_embeded\Lib\site-packages\albumentations\__init__.py:13: UserWarning: A new version of Albumentations is available: 1.4.17 (you have 1.4.16). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()

2024-10-02 06:38:55,263 - py.warnings - WARNING - E:\Stable-Diffusion\ComfyUI\python_embeded\Lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(

2024-10-02 06:38:59,994 - root - INFO - 
Import times for custom nodes:
2024-10-02 06:38:59,994 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\SDXLAspectRatio.py
2024-10-02 06:38:59,994 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\rembg-comfyui-node
2024-10-02 06:38:59,994 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\highresfix.py
2024-10-02 06:38:59,994 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\canvas_tab
2024-10-02 06:38:59,994 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-10-02 06:38:59,994 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-02 06:38:59,994 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-10-02 06:38:59,994 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SDXL-EmptyLatentImage
2024-10-02 06:38:59,994 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-10-02 06:38:59,994 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\sdxl-recommended-res-calc
2024-10-02 06:38:59,994 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\image-resize-comfyui
2024-10-02 06:38:59,994 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Noise
2024-10-02 06:38:59,994 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Logic
2024-10-02 06:38:59,994 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\cg-use-everywhere
2024-10-02 06:38:59,994 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\sdxl_prompt_styler
2024-10-02 06:38:59,994 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUi_NNLatentUpscale
2024-10-02 06:38:59,996 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\sd-dynamic-thresholding
2024-10-02 06:38:59,996 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-10-02 06:38:59,996 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\qq-nodes-comfyui
2024-10-02 06:38:59,996 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
2024-10-02 06:38:59,996 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\stability-ComfyUI-nodes
2024-10-02 06:38:59,996 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyLiterals
2024-10-02 06:38:59,996 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
2024-10-02 06:38:59,996 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis
2024-10-02 06:38:59,996 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_InstantID
2024-10-02 06:38:59,996 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ymc-node-suite-comfyui
2024-10-02 06:38:59,996 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-10-02 06:38:59,996 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_JPS-Nodes
2024-10-02 06:38:59,996 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
2024-10-02 06:38:59,996 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ControlAltAI-Nodes
2024-10-02 06:38:59,996 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\images-grid-comfy-plugin
2024-10-02 06:38:59,996 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-ZHO
2024-10-02 06:38:59,997 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\comfyui-animatediff
2024-10-02 06:38:59,997 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-10-02 06:38:59,997 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyMath
2024-10-02 06:38:59,997 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\mikey_nodes
2024-10-02 06:38:59,997 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-10-02 06:38:59,997 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\comfy-image-saver
2024-10-02 06:38:59,997 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials
2024-10-02 06:38:59,997 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-10-02 06:38:59,997 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-10-02 06:38:59,997 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-10-02 06:38:59,997 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-10-02 06:38:59,997 - root - INFO -    0.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
2024-10-02 06:38:59,997 - root - INFO -    0.1 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-10-02 06:38:59,997 - root - INFO -    0.1 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
2024-10-02 06:38:59,997 - root - INFO -    0.1 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
2024-10-02 06:38:59,997 - root - INFO -    0.1 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper
2024-10-02 06:38:59,998 - root - INFO -    0.1 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-10-02 06:38:59,998 - root - INFO -    0.1 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-10-02 06:38:59,998 - root - INFO -    0.1 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\comfy_mtb
2024-10-02 06:38:59,998 - root - INFO -    0.2 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\comfyui_segment_anything
2024-10-02 06:38:59,998 - root - INFO -    0.2 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node
2024-10-02 06:38:59,998 - root - INFO -    0.2 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\comfyui-dream-project
2024-10-02 06:38:59,998 - root - INFO -    0.4 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-02 06:38:59,998 - root - INFO -    0.6 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-N-Nodes
2024-10-02 06:38:59,998 - root - INFO -    0.8 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-10-02 06:38:59,998 - root - INFO -    1.0 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus
2024-10-02 06:38:59,998 - root - INFO -    1.1 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use
2024-10-02 06:38:59,998 - root - INFO -    1.5 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL
2024-10-02 06:38:59,998 - root - INFO -    1.7 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Allor
2024-10-02 06:38:59,998 - root - INFO -    1.9 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture
2024-10-02 06:38:59,998 - root - INFO -    2.4 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-10-02 06:38:59,998 - root - INFO -    2.9 seconds: E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes
2024-10-02 06:38:59,998 - root - INFO - 
2024-10-02 06:39:00,018 - root - INFO - Starting server

2024-10-02 06:39:00,018 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-02 06:39:30,700 - root - INFO - got prompt
2024-10-02 06:39:30,731 - root - INFO - Using pytorch attention in VAE
2024-10-02 06:39:30,733 - root - INFO - Using pytorch attention in VAE
2024-10-02 06:39:54,724 - root - ERROR - !!! Exception during processing !!! Error no file named scheduler_config.json found in directory E:\Stable-Diffusion\ComfyUI\ComfyUI\models\diffusers\Kolors.
2024-10-02 06:39:54,735 - root - ERROR - Traceback (most recent call last):
  File "E:\Stable-Diffusion\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\Stable-Diffusion\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper\nodes.py", line 77, in loadmodel
    scheduler = EulerDiscreteScheduler.from_pretrained(model_path, subfolder= 'scheduler')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI\python_embeded\Lib\site-packages\diffusers\schedulers\scheduling_utils.py", line 150, in from_pretrained
    config, kwargs, commit_hash = cls.load_config(
                                  ^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 373, in load_config
    raise EnvironmentError(
OSError: Error no file named scheduler_config.json found in directory E:\Stable-Diffusion\ComfyUI\ComfyUI\models\diffusers\Kolors.

2024-10-02 06:39:54,737 - root - INFO - Prompt executed in 24.04 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":15,"last_link_id":18,"nodes":[{"id":10,"type":"VAEDecode","pos":{"0":1368,"1":369},"size":{"0":210,"1":50},"flags":{},"order":6,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":18},{"name":"vae","type":"VAE","link":12,"slot_index":1}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[13],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":14,"type":"KolorsSampler","pos":{"0":1011,"1":371},"size":{"0":320,"1":270},"flags":{},"order":5,"mode":0,"inputs":[{"name":"kolors_model","type":"KOLORSMODEL","link":16},{"name":"kolors_embeds","type":"KOLORS_EMBEDS","link":17},{"name":"latent","type":"LATENT","link":null}],"outputs":[{"name":"latent","type":"LATENT","links":[18],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"KolorsSampler"},"widgets_values":[1024,1024,1000102404233412,"fixed",25,5,"EulerDiscreteScheduler",1]},{"id":3,"type":"PreviewImage","pos":{"0":1366,"1":468},"size":{"0":540,"1":560},"flags":{},"order":7,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":13}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":12,"type":"KolorsTextEncode","pos":{"0":519,"1":529},"size":{"0":460,"1":230},"flags":{},"order":4,"mode":0,"inputs":[{"name":"chatglm3_model","type":"CHATGLM3MODEL","link":14,"slot_index":0}],"outputs":[{"name":"kolors_embeds","type":"KOLORS_EMBEDS","links":[17],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"KolorsTextEncode"},"widgets_values":["cinematic photograph of an astronaut riding a horse in space |\nillustration of a cat wearing a top hat and a scarf  |\nphotograph of a goldfish in a bowl |\nanime screencap of a red haired girl","",1]},{"id":15,"type":"Note","pos":{"0":200,"1":636},"size":{"0":273.5273742675781,"1":149.5546417236328},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[],"properties":{"text":""},"widgets_values":["Text encoding takes the most VRAM, quantization can reduce that a lot.\n\nApproximate values I have observed:\nfp16 - 12 GB\nquant8 - 8-9 GB\nquant4 - 4-5 GB\n\nquant4 reduces the quality quite a bit, 8 seems fine"],"color":"#432","bgcolor":"#653"},{"id":11,"type":"VAELoader","pos":{"0":1323,"1":240},"size":{"0":320,"1":60},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"VAE","type":"VAE","links":[12],"shape":3}],"properties":{"Node name for S&R":"VAELoader"},"widgets_values":["sdxl_vae.safetensors"]},{"id":13,"type":"DownloadAndLoadChatGLM3","pos":{"0":206,"1":522},"size":{"0":270,"1":60},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"chatglm3_model","type":"CHATGLM3MODEL","links":[14],"shape":3}],"properties":{"Node name for S&R":"DownloadAndLoadChatGLM3"},"widgets_values":["quant8"]},{"id":6,"type":"DownloadAndLoadKolorsModel","pos":{"0":201,"1":368},"size":{"0":320,"1":80},"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"kolors_model","type":"KOLORSMODEL","links":[16],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"DownloadAndLoadKolorsModel"},"widgets_values":["Kwai-Kolors/Kolors","fp16"]}],"links":[[12,11,0,10,1,"VAE"],[13,10,0,3,0,"IMAGE"],[14,13,0,12,0,"CHATGLM3MODEL"],[16,6,0,14,0,"KOLORSMODEL"],[17,12,0,14,1,"KOLORS_EMBEDS"],[18,14,0,10,0,"LATENT"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.7247295000000004,"offset":[130.39113060068976,-12.310094055668316]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
![Screenshot 2024-10-02 064018](https://github.com/user-attachments/assets/ffdb2426-feca-4327-bf77-5694de05f9f3)

**Comment by ql0wn4** [comment]
Nobody cares?
