### ISSUE TITLE
Error when execute demo example!

### ISSUE THREAD

**Issue by CN-COTER** [Kwai-Kolors/Kolors#42]
When execute: 
`
python3 scripts/sample.py "一张瓢虫的照片，微距，变焦，高质量，电影，拿着一个牌子，写着“可图”"
`

Traceback (most recent call last):
  File "scripts/sample.py", line 42, in <module>
    fire.Fire(infer)
  File "/root/miniconda3/envs/kolors/lib/python3.8/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/kolors/lib/python3.8/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/kolors/lib/python3.8/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "scripts/sample.py", line 29, in infer
    image = pipe(
  File "/root/miniconda3/envs/kolors/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/kolors/lib/python3.8/site-packages/kolors-0.1-py3.8.egg/kolors/pipelines/pipeline_stable_diffusion_xl_chatglm_256.py", line 714, in __call__
    ) = self.encode_prompt(
  File "/root/miniconda3/envs/kolors/lib/python3.8/site-packages/kolors-0.1-py3.8.egg/kolors/pipelines/pipeline_stable_diffusion_xl_chatglm_256.py", line 328, in encode_prompt
    output = text_encoder(
  File "/root/miniconda3/envs/kolors/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/kolors/lib/python3.8/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/miniconda3/envs/kolors/lib/python3.8/site-packages/kolors-0.1-py3.8.egg/kolors/models/modeling_chatglm.py", line 835, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "/root/miniconda3/envs/kolors/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/kolors/lib/python3.8/site-packages/kolors-0.1-py3.8.egg/kolors/models/modeling_chatglm.py", line 645, in forward
    layer_ret = layer(
  File "/root/miniconda3/envs/kolors/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/kolors/lib/python3.8/site-packages/kolors-0.1-py3.8.egg/kolors/models/modeling_chatglm.py", line 549, in forward
    attention_output, kv_cache = self.self_attention(
  File "/root/miniconda3/envs/kolors/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/kolors/lib/python3.8/site-packages/kolors-0.1-py3.8.egg/kolors/models/modeling_chatglm.py", line 446, in forward
    context_layer = self.core_attention(query_layer, key_layer, value_layer, attention_mask)
  File "/root/miniconda3/envs/kolors/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/kolors/lib/python3.8/site-packages/kolors-0.1-py3.8.egg/kolors/models/modeling_chatglm.py", line 259, in forward
    matmul_result = torch.baddbmm(
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasGemmStridedBatchedExFix( handle, opa, opb, m, n, k, (void*)(&falpha), a, CUDA_R_16F, lda, stridea, b, CUDA_R_16F, ldb, strideb, (void*)(&fbeta), c, CUDA_R_16F, ldc, stridec, num_batches, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`

**Comment by 1030zero** [comment]
![image](https://github.com/user-attachments/assets/75f098c9-a01b-4a91-921f-83893af0d65d)
你好请问这个错误您遇到了么？

**Comment by CN-COTER** [comment]
> ![image](https://private-user-images.githubusercontent.com/142073348/348206671-75f098c9-a01b-4a91-921f-83893af0d65d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MjgxOTMsIm5iZiI6MTcyMTYyNzg5MywicGF0aCI6Ii8xNDIwNzMzNDgvMzQ4MjA2NjcxLTc1ZjA5OGM5LWEwMWItNGE5MS05MjFmLTgzODkzYWYwZDY1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQwNTU4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNThmYjZhY2FlMzBkNWRkYzQ3OWU2NDc0ZjQwNDcyOGY3NjgxYjc2MDQ0Mjk3NWM0Mzk4ZGFkN2U2YzFhYzc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZrKC51vOyVoewM190Zf5IS91L9sCfAR-7GTs9BJE9Jg) 你好请问这个错误您遇到了么？


严格按照这个流程走，我这边现在没有遇到任何问题。

`
  apt-get install git-lfs
  git clone https://github.com/Kwai-Kolors/Kolors
  cd Kolors
  conda create --name kolors python=3.8
  conda activate kolors
  pip install -r requirements.txt
  python3 setup.py install
`
