### ISSUE TITLE
RuntimeError: Added route will never be executed, method POST is already registered

### ISSUE THREAD

**Issue by Shihiu-Lin** [Kwai-Kolors/Kolors#50]
Import times for custom nodes:
   0.0 seconds: H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation
   0.0 seconds: H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation-main
   0.0 seconds: H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Kolors-MZ
   0.0 seconds: H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler-main
   0.0 seconds: H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts-main
   0.0 seconds: H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.1 seconds: H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.1 seconds (IMPORT FAILED): H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID
   0.4 seconds: H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   2.6 seconds: H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet-master

Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\main.py", line 225, in <module>
    server.add_routes()
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\server.py", line 565, in add_routes
    self.app.add_routes(api_routes)
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 373, in add_routes
    return self.router.add_routes(routes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_urldispatcher.py", line 1214, in add_routes
    registered_routes.extend(route_def.register(self))
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_routedef.py", line 76, in register
    return [reg(self.path, self.handler, **self.kwargs)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_urldispatcher.py", line 1180, in add_post
    return self.add_route(hdrs.METH_POST, path, handler, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_urldispatcher.py", line 1115, in add_route
    return resource.add_route(method, handler, expect_handler=expect_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_urldispatcher.py", line 356, in add_route
    raise RuntimeError(
RuntimeError: Added route will never be executed, method POST is already registered

H:\ComfyUI\ComfyUI_windows_portable>pause
請按任意鍵繼續 . . .

**Comment by Shihiu-Lin** [comment]
抱歉不是這個可圖的問題，是跟其他的nodes衝突了，把所有節點都移除，可以正常啟動

Import times for custom nodes:
   0.0 seconds: H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler-main
   0.0 seconds: H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Kolors-MZ
   0.0 seconds: H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.4 seconds: H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   2.0 seconds: H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
 [DONE]
